### ISSUE TITLE
UPPER // не может закрыть unismev если надо

### ISSUE THREAD

**Issue by majorgleb** [T-Soft/unismev#39]
при попытке снять Upper'ом  unismev получаем запрос на сохранение лога и подтверждение выхода

**Comment by T-Soft** [comment]
Maybe add a ForcedClose option?

**Comment by majorgleb** [comment]
Re: [T-Soft/unismev] UPPER // не может закрыть unismev если надо (#39)


Здравствуйте, Tony.

Вы писали 25 октября 2017 г., 10:45:58:





Maybe add a ForcedClose option?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.



а что такое опция ФорседСлоуз?
нужно просто тупо снять задачу так, чтобы она не сопротивлялась и не переспрашивала "точно ли ты меня хочешь снять?" -- Upper он же как Коржик -- если хочет он снять, значит он снимает.


-- 
С уважением,
 Gleb                          mailto:gleb@crc.ru

**Comment by T-Soft** [comment]
Добавил параметр командной строки "-no_closing_question". Если программу запстить с ним, то вопрос о закрытии задаваться не будет

**Comment by T-Soft** [comment]
Поправка. Параметр выглядит так: "--no_closing_query"
