### ISSUE TITLE
URGENT ns + REJECT-message // средне-срочно по времени реализации

### ISSUE THREAD

**Issue by majorgleb** [T-Soft/unismev#59]
При работе urgent ns не предусмотрена возможность передачи сообщения типа REJECT - есть только "позитивный" ответ. Нужно придумать как расширить возможности ответа ургент скрипта - чтобы иметь возможность ответить бизнес логикой с установленным призхнаком REJECT (как это уже есть у resnond)

**Comment by majorgleb** [comment]
думаю, может сделать так
сейчас [~{base64}] - это ответ в стиле ОК
а сделать дополнительно [~~{OK|REJECT {строка-код из МР для Reject} {base 64 текста для descriptions}~{base64 buisness body | пусто}]

например

[~~OK~тут_base64_бизнес_ответа] аналог [~тут_base64_бизнес_ответа]

[~~REJECT NO_DATA base64_теста_для_descriptions~тут_base64_бизнес_ответа]
[~~REJECT ACCESS_DENIED base64_теста_для_descriptions]

т.е. сразу за REJECT идет то (код), что помещается в элемент RejectionReasonCode
а строка из base64 за кодом помещается в RejectionReasonDescription

если СМЭВ придумает еще какие действия -- то кроме OK/REJECT появится еще что-то

**Comment by majorgleb** [comment]
блин этот хренов редактор!! я ничего не зачеркивал! лучше голосом поясню что имел в виду

**Comment by T-Soft** [comment]
Редактор не виноват в том, что ты не читал мануал по тому, как им пользоваться)) ~текст между тильдами~ будет зачеркнутым - это Markdown - упрощенный язык разметки))

**Comment by T-Soft** [comment]
Also please note that instead of one space **several spaces could be used** to separate response parts
