### ISSUE TITLE
"Падение" unismev // несанкционированное прекращение работы

### ISSUE THREAD

**Issue by majorgleb** [T-Soft/unismev#75]
Есть предположение, что unismev падает в момент когда "отсутствует интернет" - т.е. или упал канал до СМЭВ (как это было сегодня когда перетыкали провода) или когда отсутствует ip адреса "единого окна" смэв-3

Причем это очень важный момент - что если uni может остлеживать "целостность" канало до СМЭВ-3 -- это нужно логировать отдельно. И нужно обсудить как именно.

**Comment by T-Soft** [comment]
Added more exception handling to Send() method
