### ISSUE TITLE
core // новый дополнительный файл-флаг *.OriginalMessageId.flag для приходящих response 

### ISSUE THREAD

**Issue by majorgleb** [T-Soft/unismev#87]
для определенных ns (те указание через конфиг по каждому ns отьедьно) указывается необходимость создания кроме арбайтен флага еще и OriginalMessageId-флага

например:
031f0a8f-8b5f-11e8-8d42-005056ad53ff.arbeiten.flag содержание: [\PSMEV\.\data\OUT_FNS_egrip_PSMEV\2018\07\19\031f0a8f-8b5f-11e8-8d42-005056ad53ff.xml]

f1ec845c-8b5e-11e8-9f50-d2aee60d280d.OriginalMessageId.flag содержание:  [031f0a8f-8b5f-11e8-8d42-005056ad53ff]

т.к. у арбайтен фалага UUID в имени это messageId самого xml с ответов, а требуетсяиногда искать по messageId запроса

т.о. когда приходит response то юни для отдельных ns создает ***..OriginalMessageId.flag  где *** 'это и есть OriginalMessageId из response
а соджержание - это messageId ответа как xml файла

заинтересованное лицо по своему UUID запроса ищет .OriginalMessageId.flag после чего прочтя его понимает какой именно арбайтен-флаг искать

**Comment by T-Soft** [comment]
Added option on the namsepace level <is_create_omid_flag> to create OriginalMessageId.flag

**Comment by majorgleb** [comment]
Ok, протестировал. Поставил на трех ВС ФНС (ЕГРИП/ЕГРЮЛ/ЕГРИП адр) в боевое дежурство
