### ISSUE TITLE
config + FTP // ключ для ns по принудительному отключению получения FTP

### ISSUE THREAD

**Issue by majorgleb** [T-Soft/unismev#92]
Нужен ключ в конфиг который отключит для конкретного ns получение FTP данных, даже если они есть. по сути - игнорирование наличия FTP

совершенно аварийный ключ, т.к. по хорошему тянуть надо всё

**Comment by T-Soft** [comment]
Config key for namespace is
<is_skip_ftp_download>1</is_skip_ftp_download>
