### ISSUE TITLE
UI // "палец" как курсор мыши на активных элементах интерфейса

### ISSUE THREAD

**Issue by majorgleb** [T-Soft/unismev#93]
Может быть стоит на всех активных элементах UI менять курсор на "палец", чтобы было ясно что ЭТО именно элемент управления.
Причина в том, что то что "дискета" нажимается -- хрен поймешь, если ты бы не сказал :)

**Comment by majorgleb** [comment]
По практике выяснилось -- что хорошо бы еще не только палец показать, но и подсветить цветом фона hover-элемент. Возможно?

**Comment by T-Soft** [comment]
Done
